language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: TimesheetApplication.sln

before_install: 
  - npm install -g webpack
  - npm link webpack

before-script: 
  - nuget restore TimesheetApplication.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner

script:
 - dotnet restore
 - dotnet test XUnitTestProject/XUnitTestProject.csproj
 
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

deploy:
  provider: azure_web_apps
  on: 
    branch: master
  username: username       # If AZURE_WA_USERNAME isn't set
  password: password
  site: TimesheetApplication
