language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: TimesheetApplication.sln

before-script: 
  - nuget restore TimesheetApplication.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner
  - npm install -g webpack 

script:
 - dotnet restore
 - dotnet test XUnitTestProject/XUnitTestProject.csproj
 
notifications:
  slack:
    rooms:
      - infosys-2017:TVvKGNzlz8ScmVpQxfX7wadf#voldemort_builds
      - infosys-2017:TVvKGNzlz8ScmVpQxfX7wadf#testing

 
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
